openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8080'
    description: Generated server url
tags:
  - name: Register device
    description: Register device from MobileApp
paths:
  /api/v1/register-device/send:
    post:
      tags:
        - Register device
      summary: Register device
      description: Register device from MobileApp
      operationId: sendMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register device'
        required: true
      responses:
        '200':
          description: Message received successfully
          content:
            '*/*':
              schema:
                type: string
        '400':
          description: Bad request
          content:
            '*/*':
              schema:
                type: string
  /api/v1/messages/send:
    post:
      tags:
        - OMS Messages
      summary: Receive a message
      description: Receive a message
      operationId: receiveMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageOMS'
        required: true
      responses:
        '200':
          description: Message received successfully
          content:
            '*/*':
              schema:
                type: string
        '400':
          description: Bad request
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Register device:
      required:
        - benutzername
        - deviceID
      type: object
      properties:
        benutzername:
          type: string
          description: Username
          example: aeral.energie@aeral.de
        deviceID:
          type: string
          description: Device ID from MobileApp
          example: 32FDAAFEA8CC86016
      description: Register device from MobileApp
    MessageOMS:
      required:
        - kundenID
        - nachricht
      type: object
      properties:
        kundenID:
          type: string
          description: Client ID
          example: '123456782'
        nachricht:
          type: string
          description: Massage from OMS
          example: >-
            Hallo Herr Drewes, Sie haben ein neues Dokument in Ihrer Postbox
            erstellt. Vielen Dank!
      description: Massage from OMS